---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggthemes)
```

```{r}
# Read as CSV the file everytime
heart2020 <- read_csv(file = "heart_2020_cleaned.csv")
```

```{r}
genderplot <- heart2020 |>
  # We only care about age and sex in relation to heart disease, nothing else
  group_by(AgeCategory, Sex)|>
  # This creates a percentage of people with heart disease/aka those who answer "Yes" Use .groups = to drop the error message
  summarize(PercentageofHD = mean(HeartDisease == "Yes"), .groups = "drop") |>
  # Making the plot: important note is group = which groups the lines by Sex
  ggplot(mapping = aes(x = AgeCategory, y = PercentageofHD, group = Sex, color = Sex)) +
  geom_line(size = 1) +
  geom_point() +
  # This changes the x-axis marks
 scale_x_discrete(breaks = c("18-24", "30-34", "40-44", "50-54", "60-64", "70-74", "80 or older")) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) +
  labs(title = "The Age Distribution of People With Heart Disease",
       subtitle = "Risk for Heart Problems Increases With Age",
       x = "Age",
       y = "Percentage Heart Disease") +
  # Messes with the fonts of the graph
  theme(plot.title = element_text(face = "bold"),
          axis.text = element_text(face = "bold"), 
          axis.title.x = element_text(face = "bold"),
          axis.title.y = element_text(face = "bold"))
```

```{r}
write_rds(genderplot, "genderplot.rds")
```

